### PR TITLE
[DNM] Don't allow empty terms to be added to Fingerprint

### PR DESCRIPTION
**Pull request by Benestar**
Missing tests

This only checks in `setLabel`, `setDescription` and `setAliases` but not in the constructor.

[Bug: T121433](https://phabricator.wikimedia.org/T121433)

### CODE REVIEW

**Comment by thiemowmde** [comment]
This goes along with https://github.com/wmde/WikibaseDataModel/pull/579 and should only be merged when that other change is discussed and merged. Personally I like this.

**Comment by brightbyte** [comment]
Looks good, but we should have qunit tests for this.

**Comment by brightbyte** [comment]
Why is this tagged as "do not merge"?

**Comment by thiemowmde** [comment]
Because of "missing tests".

**Comment by Benestar** [comment]
Closing this and reopening against master.

**Pull request closed without merging**
