### PR TITLE
Remove fingerprint from Entity - Depends on #85

### PR DESCRIPTION
**Pull request by tarrow**
Remove references to fingerprint from Entity.

Depends on #85

### CODE REVIEW

**Comment by mariushoch** [comment]
+2: Looks good to be merged (once the conflicts are resolved)!

**Comment by wiese** [comment]
Will leave this here for Monday https://upload.wikimedia.org/wikipedia/commons/c/c2/Wikibase_JavaScript_Data_Model_1.0.svg

**Comment by tarrow** [comment]
@wiese Are you thinking it should be removed since it's very old? Looks like the map/link hasn't been updated since October 2014.

**Comment by wiese** [comment]
@tarrow Not removing but making a discipline of updating it when we publish a release - it is also part of our own documentation so having it outdated would be detrimental to its intended purpose. One more question for next Monday.

**Pull request merged**
