### PR TITLE
Use extension registration for MediaWiki credits

### PR DESCRIPTION
**Pull request by filbertkm**
also fixes broken license link on Special:Version

### CODE REVIEW

**Comment by thiemowmde** [comment]
Looks good, but I suggest to rename all LICEN[CS]E files to COPYING, because this file name is way more common across our components.

**Comment by thiemowmde** [comment]
Also see the discussion at https://github.com/wmde/WikibaseInternalSerialization/pull/91.

**Comment by addshore** [comment]
*agrees with changing it to COPYING*

**Comment by thiemowmde** [comment]
+2, but this is a breaking change because of the removal of the constant. We could merge this faster with the constant marked as deprecated.

**Comment by filbertkm** [comment]
it is not so urgent to merge this

**Comment by thiemowmde** [comment]
I re-added the constant and marked it as deprecated.

**Pull request merged**
