### PR TITLE
Lint code using eslint instead of jshint

### PR DESCRIPTION
**Pull request by manicki**
Task: https://phabricator.wikimedia.org/T165843

### CODE REVIEW

**Comment by thiemowmde** [comment]
Travis still iterates into the node_modules/… directory and complains. Do you know how to fix this?

**Comment by manicki** [comment]
I have no idea ATM. Didn't happen for me locally, I am not sure what did I mess up.

**Comment by Ladsgroup** [comment]
It says it can not install eslint now: https://travis-ci.org/wmde/WikibaseDataModelJavaScript/builds/238402279

**Comment by manicki** [comment]
OK, it was failing because it is build as a PHP project, and PHP VMs have an old node version which is incompatible with eslint version used.
After several attempts I managed to get this work. It is is a bit hacky and rather fragile. OTOH I believe I understand the reason behind distributing a JS library as as package on packagist. Hopefully one day this all will be installed with npm and so on.

**Comment by JeroenDeDauw** [comment]
> distributing a JS library as as package on packagist

The way it's written it's a MW extension, not a JS lib

**Comment by manicki** [comment]
oh, of course. Silly me.
Then I guess having a PHP build with installing new-enough node is probably the best we can get for now.

**Comment by thiemowmde** [comment]
Do you think this is fine to be merged as it is now? Looks fine for me. Is there something we can improve about the "fragile" bits you mentioned?

**Comment by manicki** [comment]
> Do you think this is fine to be merged as it is now?

Yes.

> Is there something we can improve about the "fragile" bits you mentioned?

Nothing particular I can think of now.

**Pull request merged**
