### PR TITLE
Update release notes for 4.0.0 (dev)

### PR DESCRIPTION
**Pull request by manicki**

### CODE REVIEW

**Comment by thiemowmde** [comment]
We piled up some more changes that have not been mentioned in the README so far: #71, and #73. At least #73 is a breaking change and requires a major version bump. I would love to add a few more changes to this release, if possible. At least #74. Possibly (but not necessarily) #40. Can we do this?

**Comment by manicki** [comment]
Right, I didn't check the master history and didn't notice README is incomplete. To be honest, I don't think I am not going to have a chance to dive into this lib and those open PRs. The only reason I wanted to do the 3.1.0 release was the fact it is required for the following task https://phabricator.wikimedia.org/T171725. I guess I'd rather make a smaller 3.1.0 excluding breaking changes to not block the linked task.

**Comment by thiemowmde** [comment]
@manicki, I updated this pull request to be an update for master, independent from the 3.x branch. Do you think it's ok if I merge this myself?

**Comment by manicki** [comment]
IMO itt would have been fine if you just pushed it to master even skipping PR as we're not about do the 4.0.0 release yet.

**Pull request merged**
